package iniuas;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class FormDataWarga extends javax.swing.JInternalFrame {

    private final DataWarga db = new DataWarga();
    
    private void updateTable() {
    
        DefaultTableModel tbl = (DefaultTableModel) tabelDataWarga.getModel();
    
        tbl.setNumRows(0);
        
        try {
            
            db.refresh();
            
            while(db.hasil.next()) {
                
                tbl.addRow(new Object[]{
                    
                    db.hasil.getString("nomor_rumah"),
                    db.hasil.getString("nama_kepala_keluarga"),
                    db.hasil.getString("nomor_telepon"),
                    db.hasil.getString("alamat"),
                    db.hasil.getString("status")
                        
                });
                                
            }
            
                db.hasil.close();

        }
                    
        catch (Exception ex) {JOptionPane.showMessageDialog (null, "data error" +ex.getMessage());}

        }
    
    private void clearTextField() {
        
        textNomorRumah.setText("");
        textNamaKepalaKeluarga.setText("");
        textNomorTelepon.setText("");
        textAlamat.setText("");
        
    }
    
    /**
     * Creates new form FormDataWarga
     */
    public FormDataWarga() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelDataWarga = new javax.swing.JTable();
        textNomorRumah = new javax.swing.JTextField();
        textNamaKepalaKeluarga = new javax.swing.JTextField();
        textNomorTelepon = new javax.swing.JTextField();
        textAlamat = new javax.swing.JTextField();
        tombolTambah = new javax.swing.JButton();
        tombolUpdate = new javax.swing.JButton();
        tombolHapus = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Form Data Warga");
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Nomor Rumah");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Nama Kepala Keluarga");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Nomor Telepon/WA");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Alamat");

        tabelDataWarga.setBackground(new java.awt.Color(255, 255, 204));
        tabelDataWarga.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nomor Rumah", "Nama Kepala Keluarga", "Nomor Telepon/WA", "Alamat", "Status Iuran"
            }
        ));
        tabelDataWarga.setGridColor(new java.awt.Color(204, 255, 204));
        tabelDataWarga.setSelectionBackground(new java.awt.Color(204, 255, 204));
        tabelDataWarga.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelDataWargaMouseClicked(evt);
            }
        });
        tabelDataWarga.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tabelDataWargaKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tabelDataWarga);

        textNomorRumah.setBackground(new java.awt.Color(255, 255, 204));

        textNamaKepalaKeluarga.setBackground(new java.awt.Color(255, 255, 204));

        textNomorTelepon.setBackground(new java.awt.Color(255, 255, 204));

        textAlamat.setBackground(new java.awt.Color(255, 255, 204));

        tombolTambah.setBackground(new java.awt.Color(204, 255, 204));
        tombolTambah.setText("Tambah Data");
        tombolTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolTambahActionPerformed(evt);
            }
        });

        tombolUpdate.setBackground(new java.awt.Color(204, 255, 204));
        tombolUpdate.setText("Update Data");
        tombolUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolUpdateActionPerformed(evt);
            }
        });

        tombolHapus.setBackground(new java.awt.Color(204, 255, 204));
        tombolHapus.setText("Hapus Data");
        tombolHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolHapusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(textNomorRumah, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
                    .addComponent(textNamaKepalaKeluarga)
                    .addComponent(textNomorTelepon)
                    .addComponent(textAlamat))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tombolUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                    .addComponent(tombolHapus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tombolTambah, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(39, 39, 39))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textNomorRumah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tombolTambah)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(textNamaKepalaKeluarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tombolUpdate))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(textNomorTelepon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(textAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(tombolHapus, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tombolUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolUpdateActionPerformed
        
        String cekNomorRumah, cekNamaKepalaKeluarga, cekNomorTelepon, cekAlamat;
            
            cekNomorRumah = textNomorRumah.getText();
            cekNamaKepalaKeluarga = textNamaKepalaKeluarga.getText();
            cekNomorTelepon = textNomorTelepon.getText();
            cekAlamat = textAlamat.getText();
            
            try{
                
                db.update(cekNomorRumah, cekNamaKepalaKeluarga, cekNomorTelepon, cekAlamat); 
                updateTable();
                
                JOptionPane.showMessageDialog(this, "Data sudah di Update!");
            }
            
            catch (Exception ex) {}
            
    }//GEN-LAST:event_tombolUpdateActionPerformed

    private void tombolTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolTambahActionPerformed
        
        String cekNomorRumah, cekNamaKepalaKeluarga, cekNomorTelepon, cekAlamat;
        
        cekNomorRumah = textNomorRumah.getText();
        cekNamaKepalaKeluarga = textNamaKepalaKeluarga.getText();
        cekNomorTelepon = textNomorTelepon.getText();
        cekAlamat = textAlamat.getText();
        
        db.cek(cekNomorRumah);
        
        try{
        
        if(db.hasil.next()) {
        JOptionPane.showMessageDialog(this, "Data sudah ada!");}
        
        else {
        
            db.tambah(cekNomorRumah, cekNamaKepalaKeluarga, cekNomorTelepon, cekAlamat);
            
            updateTable();
            clearTextField();
            
            JOptionPane.showMessageDialog(this, "Data sudah disimpan!");
            
            }
        }
    
            catch (Exception ex) {}
        
    }//GEN-LAST:event_tombolTambahActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        updateTable();
    }//GEN-LAST:event_formComponentShown

    private void tabelDataWargaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tabelDataWargaKeyReleased
        
        int i = tabelDataWarga.getSelectedRow();
        
        DefaultTableModel
                
        tbl = (DefaultTableModel)tabelDataWarga.getModel();
        
        textNomorRumah.setText((String)tbl.getValueAt(i, 0));
        textNamaKepalaKeluarga.setText((String)tbl.getValueAt(i, 1));
        textNomorTelepon.setText((String)tbl.getValueAt(i, 2));
        textAlamat.setText((String)tbl.getValueAt(i, 3));
        
        
    }//GEN-LAST:event_tabelDataWargaKeyReleased

    private void tabelDataWargaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelDataWargaMouseClicked
        
        int i = tabelDataWarga.getSelectedRow();
        
        DefaultTableModel
        
        tbl = (DefaultTableModel)tabelDataWarga.getModel();
        
        textNomorRumah.setText((String)tbl.getValueAt(i, 0));
        textNamaKepalaKeluarga.setText((String)tbl.getValueAt(i, 1));
        textNomorTelepon.setText((String)tbl.getValueAt(i, 2));
        textAlamat.setText((String)tbl.getValueAt(i, 3));
        
    }//GEN-LAST:event_tabelDataWargaMouseClicked

    private void tombolHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolHapusActionPerformed
        
        String cekNomorRumah;

        cekNomorRumah = textNomorRumah.getText();

        try{

            db.hapus(cekNomorRumah);

            updateTable();

            clearTextField();

            JOptionPane.showMessageDialog(this, "Data sudah di Hapus!");

        }

        catch (Exception ex) {}
        
    }//GEN-LAST:event_tombolHapusActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelDataWarga;
    private javax.swing.JTextField textAlamat;
    private javax.swing.JTextField textNamaKepalaKeluarga;
    private javax.swing.JTextField textNomorRumah;
    private javax.swing.JTextField textNomorTelepon;
    private javax.swing.JButton tombolHapus;
    private javax.swing.JButton tombolTambah;
    private javax.swing.JButton tombolUpdate;
    // End of variables declaration//GEN-END:variables
}
