package iniuas;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class FormBayarIuranBulanan extends javax.swing.JInternalFrame {
    
    private final DataBayarIuranBulanan db = new DataBayarIuranBulanan();
    
    private void updateTable() {
    
        DefaultTableModel tbl = (DefaultTableModel) tabelDataIuran.getModel();
    
        tbl.setNumRows(0);
        
        try {
            
            while(db.hasil.next()) {
                
                tbl.addRow(new Object[]{
                    
                    db.hasil.getString("nomor_rumah"),
                    db.hasil.getString("nama_kepala_keluarga"),
                    db.hasil.getString("nominal_bayar"),
                    db.hasil.getString("keterangan"),
                    db.hasil.getString("status")
                        
                });
                                
            }
            
              db.hasil.close();

        }
                    
        catch (Exception ex) {JOptionPane.showMessageDialog (null, "data error" +ex.getMessage());}

        }
    
    private void clearTextField() {
        
        textNomorRumah.setText("");
        textNamaKepalaKeluarga.setText("");
        textNominalBayar.setText("");
        textKeterangan.setText("");
        listStatusIuran.setSelectedIndex(0);
        
    }

    /**
     * Creates new form FormBayarIuranBulanan
     */
    public FormBayarIuranBulanan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textNominalBayar = new javax.swing.JTextField();
        tombolTambah = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        tombolUpdate = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        tombolHapus = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        textNamaKepalaKeluarga = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        textKeterangan = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelDataIuran = new javax.swing.JTable();
        textNomorRumah = new javax.swing.JTextField();
        listStatusIuran = new javax.swing.JComboBox<>();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Bayar Iuran Bulanan");
        setMinimumSize(new java.awt.Dimension(750, 600));
        setPreferredSize(new java.awt.Dimension(750, 600));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        textNominalBayar.setBackground(new java.awt.Color(204, 204, 255));
        textNominalBayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNominalBayarActionPerformed(evt);
            }
        });

        tombolTambah.setText("Tambah Data");
        tombolTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolTambahActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Nomor Rumah");

        tombolUpdate.setText("Update Data");
        tombolUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolUpdateActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Nama Kepala Keluarga");

        tombolHapus.setText("Hapus Data");
        tombolHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolHapusActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Nominal Bayar");

        textNamaKepalaKeluarga.setBackground(new java.awt.Color(204, 204, 255));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Keterangan");

        textKeterangan.setBackground(new java.awt.Color(204, 204, 255));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Status Iuran");

        tabelDataIuran.setBackground(new java.awt.Color(204, 204, 255));
        tabelDataIuran.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nomor Rumah", "Nama Kepala Keluarga", "Nominal Bayar", "Keterangan", "Status Iuran"
            }
        ));
        tabelDataIuran.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelDataIuranMouseClicked(evt);
            }
        });
        tabelDataIuran.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tabelDataIuranKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tabelDataIuran);

        textNomorRumah.setBackground(new java.awt.Color(204, 204, 255));

        listStatusIuran.setBackground(new java.awt.Color(204, 204, 255));
        listStatusIuran.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sudah Bayar", "Belum Bayar" }));
        listStatusIuran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listStatusIuranActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 726, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textNominalBayar)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel4))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(textNomorRumah)
                                    .addComponent(textNamaKepalaKeluarga, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tombolTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tombolUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(listStatusIuran, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(textKeterangan))
                                .addGap(18, 18, 18)
                                .addComponent(tombolHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(28, 28, 28))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(textNomorRumah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2))
                    .addComponent(tombolTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(textNamaKepalaKeluarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textNominalBayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addGap(0, 1, Short.MAX_VALUE))
                    .addComponent(tombolUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(textKeterangan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addGap(4, 4, 4)
                        .addComponent(listStatusIuran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(tombolHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tombolTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolTambahActionPerformed

        String cekNomorRumah, cekNamaKepalaKeluarga, cekNominalBayar, cekKeterangan, cekStatus;
        
        cekNomorRumah = textNomorRumah.getText();
        cekNamaKepalaKeluarga = textNamaKepalaKeluarga.getText();
        cekNominalBayar = textNominalBayar.getText();
        cekKeterangan = textKeterangan.getText();
        cekStatus = listStatusIuran.getSelectedItem()+"";
        
        db.cek(cekNomorRumah);
        
        try{
        
        if(db.hasil.next()) {
        JOptionPane.showMessageDialog(this, "Data sudah ada!");}
        
        else {
        
            db.tambah(cekNomorRumah, cekNamaKepalaKeluarga, cekNominalBayar, cekKeterangan, cekStatus);
            
            updateTable();
            clearTextField();
            
            JOptionPane.showMessageDialog(this, "Data sudah disimpan!");
            
            }
        }
    
            catch (Exception ex) {}
        
    }//GEN-LAST:event_tombolTambahActionPerformed

    private void tombolUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolUpdateActionPerformed

         String cekNomorRumah, cekNamaKepalaKeluarga, cekNominalBayar, cekKeterangan, cekStatus;
            
            cekNomorRumah = textNomorRumah.getText();
            cekNamaKepalaKeluarga = textNamaKepalaKeluarga.getText();
            cekNominalBayar = textNominalBayar.getText();
            cekKeterangan = textKeterangan.getText();
            cekStatus = listStatusIuran.getSelectedItem()+"";
            
            try{
                
                db.update(cekNomorRumah, cekNominalBayar, cekKeterangan, cekStatus); 
                updateTable();
                
                JOptionPane.showMessageDialog(this, "Data sudah di Update!");
            }
            
            catch (Exception ex) {}

    }//GEN-LAST:event_tombolUpdateActionPerformed

    private void tombolHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolHapusActionPerformed

        String cekNomorRumah;

        cekNomorRumah = textNomorRumah.getText();

        try{

            db.hapus(cekNomorRumah);

            updateTable();

            clearTextField();

            JOptionPane.showMessageDialog(this, "Data sudah di Hapus!");

        }

        catch (Exception ex) {}

    }//GEN-LAST:event_tombolHapusActionPerformed

    private void tabelDataIuranMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelDataIuranMouseClicked

        int i = tabelDataIuran.getSelectedRow();
        
        DefaultTableModel
        
        tbl = (DefaultTableModel)tabelDataIuran.getModel();
        
        textNomorRumah.setText((String)tbl.getValueAt(i, 0));
        textNamaKepalaKeluarga.setText((String)tbl.getValueAt(i, 1));
        textNominalBayar.setText((String)tbl.getValueAt(i, 2));
        textKeterangan.setText((String)tbl.getValueAt(i, 3));
        listStatusIuran.setSelectedItem((String)tbl.getValueAt(i, 4));

    }//GEN-LAST:event_tabelDataIuranMouseClicked

    private void tabelDataIuranKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tabelDataIuranKeyReleased

        int i = tabelDataIuran.getSelectedRow();
        
        DefaultTableModel
                
        tbl = (DefaultTableModel)tabelDataIuran.getModel();
        
        textNomorRumah.setText((String)tbl.getValueAt(i, 0));
        textNamaKepalaKeluarga.setText((String)tbl.getValueAt(i, 1));
        textNominalBayar.setText((String)tbl.getValueAt(i, 2));
        textKeterangan.setText((String)tbl.getValueAt(i, 3));
        listStatusIuran.setSelectedItem((String)tbl.getValueAt(i, 4));

    }//GEN-LAST:event_tabelDataIuranKeyReleased

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        updateTable();
    }//GEN-LAST:event_formComponentShown

    private void textNominalBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNominalBayarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNominalBayarActionPerformed

    private void listStatusIuranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listStatusIuranActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listStatusIuranActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> listStatusIuran;
    private javax.swing.JTable tabelDataIuran;
    private javax.swing.JTextField textKeterangan;
    private javax.swing.JTextField textNamaKepalaKeluarga;
    private javax.swing.JTextField textNominalBayar;
    private javax.swing.JTextField textNomorRumah;
    private javax.swing.JButton tombolHapus;
    private javax.swing.JButton tombolTambah;
    private javax.swing.JButton tombolUpdate;
    // End of variables declaration//GEN-END:variables
}
